### ISSUE TITLE
Homework #1 and #2

### ISSUE THREAD

**Issue by aLiNaUsHaKoVa** [aLiNaUsHaKoVa/WPF2021#1]
@justjune 
Все пояснения для для работы с программой есть в папке с решением. 
Также у меня есть вопрос, если я эти программы сдавала вовремя, но забыла создать issue (и писала в OneNote), будет ли это считаться "просроченным дедлайном"?

**Comment by justjune** [comment]
Время commit считается сроком сдачи задания.
См. успеваемость.
Алина, попробуйте ответить на вопрос, который я задал вам в onenote.

**Comment by aLiNaUsHaKoVa** [comment]
@justjune
Здравствуйте. В onenote пусто, никакого вопроса нет.

**Comment by justjune** [comment]
Алина, здравствуйте. Попробуйте обновить записную книжку ванноты...

**Comment by aLiNaUsHaKoVa** [comment]
@justjune
В onenote ответила
