### ISSUE TITLE
Вопрос про коэффициент сопротивления и интерфейс. 

### ISSUE THREAD

**Issue by aLiNaUsHaKoVa** [aLiNaUsHaKoVa/WPF2021#2]
@justjune 
Здравствуйте! 
У меня появились вопросы:
1. В формулах, которые предоставили Вы, k зависит от t, а в формулах из интернета k - обычная константа. В программе используется k как константа, которая задается пользователем, но если надо сделать ее зависящей от времени, то тогда переделаю задание. 
2. Нужны ли какие-либо пояснения к интерфейсу? И если нужны, то какие? (Изображение интерфейса лежит в папке TrajectoryWithResistance)
Заранее спасибо!

**Comment by justjune** [comment]
1. В формулах, которые вы видите в Интернет k --- коэффициент сопротивления среды. В наших уравнениях ---ветровое воздействие, которое может меняться со временем.
2. Если смысл нарисованного вами интерфейса очевиден, то пояснения не нужны. Если есть подозрения, что я не догадаюсь что на изображении, то напишите пояснения.

**Comment by aLiNaUsHaKoVa** [comment]
@justjune
Здравствуйте. А как должен выглядеть коэффициент k, меняющийся со временем? Это просто какая-то величина накапливающаяся с течением времени и нам пользователь дает значение с какой скоростью в секунду это накапливается? Или пользователь дает функцию по которой вычисляется k? И если это функция, то как она должна выглядеть?

**Comment by justjune** [comment]
Мы просто считаем, что программисту сообщается определенная функция, которую он включает в свою программу. Если хочется многообразия, можно использовать указатель на функцию, которому присваивать функции разного вида.
