### ISSUE TITLE
Метод Эйлера. 

### ISSUE THREAD

**Issue by aLiNaUsHaKoVa** [aLiNaUsHaKoVa/WPF2021#3]
_Решение задачи с учетом сопротивления ветра, плюс набросок интерфейса._ 
@justjune

**Comment by aLiNaUsHaKoVa** [comment]
@justjune 
Добрый день, Сергей Иванович!
Я обнаружила некую проблему в коде: сначала все идет хорошо, координаты x и y нормальные (соответствующие: сначала возрастают, потом убывают), но в конце с координатами начинаются проблемы (они явно видны при больших значениях k), они начинают то возрастать, то убывать. Думаю, что проблема может быть с формулами проекции скорости. Например, когда Х-проекция скорости отрицательна и k(t) достаточно большой, то из-за знака минус в формуле, значение становится положительным и перевешивает Vx, из-за чего значения в последствии начинают скакать. 

![image](https://user-images.githubusercontent.com/61658563/112603013-35fbba80-8e36-11eb-893e-71f0c01ff302.png)

Что с этим можно сделать?
Заранее спасибо.

**Comment by justjune** [comment]
Алина, если значения к большие, то значит ветер может "сдувать" снаряд куда захочет...

**Comment by justjune** [comment]
Проблема в другом: ветровое воздействие k(t) подразумевает задние функции, а не константы.

**Comment by Duisus** [comment]
@justjune

Но у меня в программе ведь k(t) - это функция, которую я взяла из головы. И поэтому я не понимаю, что происходит.

**Comment by justjune** [comment]
Попробуйте описать физический смысл этой функции и ее предполагаемое воздействие на движение (она же входит в одну из сил, приложенных к телу).
