### ISSUE TITLE
Интерфейс. 

### ISSUE THREAD

**Issue by aLiNaUsHaKoVa** [aLiNaUsHaKoVa/WPF2021#5]
Здравствуйте!
У меня есть вопрос по поводу интерфейса. 
Его нужно писать прямо руками или можно будет изучить и использовать, например, xaml файлы?

**Comment by justjune** [comment]
Здравствуйте! Его **нужно** будет писать и прямо и с xaml.

**Comment by justjune** [comment]
Почему на практики не ходите? (Где можно задавать вопросы и демонстрировать возникшие проблемы?)

**Comment by aLiNaUsHaKoVa** [comment]
Здравствуйте, Сергей Иванович.  Я Вам ответила на данный вопрос в Teams.

**Comment by justjune** [comment]
Здравствуйте, Алина. Хорошо, я понял. (Встречные предложения --- тоже в Тимз.)
